### ISSUE TITLE
Some issues happen when I start this program

### ISSUE THREAD

**Issue by Mcdull0801** [lucasdavid/mazerunner#2]
Hello Lucas David, I am doing nao robot research. When I run your code, some bugs happen, could you please give me some opinions. 
Firstly, "ImportError: No module named utils" is often informed,  but I have installed utils already.
Secondly, Where is the "mazerunner/examples/navigate.py"? Although you have mentioned in Readme.md,  I can't find at all.
I'm really looking forward to your reply. Best wish.

**Comment by lucasdavid** [comment]
It's right here: [mazerunner/mazerunner/utils](https://github.com/lucasdavid/mazerunner/tree/master/mazerunner/utils)
This utils is MY utils, not some other package. Did you install this repository's code with `python setup.py install`?

As for the navigate.py file, I have updated the code and forgot to keep up with it in the README.md file. Currently, you can execute the following:

 * `training_navigator.py`: this will make the agent walk around while training the transition weights in the Q-learning table. The agent will perform random actions considering the Q-learning default training algorithm.
 * `navigate_with_trained_agent.py`: this will instantiate an agent and a Q-learning table with the weights trained by the script above. The agent, in turn, will walk around following the best policy of the table.

I must warn you, though: for some reason I couldn't make the bot walk efficiently throughout the map. I think its walk isn't quite right optimized. Let me know if you make it better! :-)

**Comment by Mcdull0801** [comment]
Thank you very much! Your work has helped me a lot, and thank you for your reply again!
